// <auto-generated />
using System;
using LifeOpsPlanner_Project.EfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeOpsPlanner_Project.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260227204455_W8_AddPerson_NullableFK")]
    partial class W8_AddPerson_NullableFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.ActivityEntry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryId"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("Untitled");

                    b.HasKey("EntryId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("PersonId");

                    b.ToTable("ActivityEntries");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.ActivityEntryTag", b =>
                {
                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("EntryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ActivityEntryTags");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.ActivityEntry", b =>
                {
                    b.HasOne("LifeOpsPlanner_Project.EfCore.Entities.Activity", "Activity")
                        .WithMany("ActivityEntries")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityEntries_Activities");

                    b.HasOne("LifeOpsPlanner_Project.EfCore.Entities.Person", "Person")
                        .WithMany("ActivityEntries")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ActivityEntries_Persons");

                    b.Navigation("Activity");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.ActivityEntryTag", b =>
                {
                    b.HasOne("LifeOpsPlanner_Project.EfCore.Entities.ActivityEntry", "ActivityEntry")
                        .WithMany("ActivityEntryTags")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeOpsPlanner_Project.EfCore.Entities.Tag", "Tag")
                        .WithMany("ActivityEntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityEntry");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.Activity", b =>
                {
                    b.Navigation("ActivityEntries");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.ActivityEntry", b =>
                {
                    b.Navigation("ActivityEntryTags");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.Person", b =>
                {
                    b.Navigation("ActivityEntries");
                });

            modelBuilder.Entity("LifeOpsPlanner_Project.EfCore.Entities.Tag", b =>
                {
                    b.Navigation("ActivityEntryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
